"""first_init

Revision ID: dd9b57ea1b53
Revises: 
Create Date: 2024-10-15 21:44:01.358917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9b57ea1b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_fin_recurrence', sa.DateTime(), nullable=True),
    sa.Column('recurrent', sa.Boolean(), nullable=False),
    sa.Column('recurrence_type', sa.String(length=80), nullable=True),
    sa.Column('recurrence_nombre_occurence', sa.Integer(), nullable=True),
    sa.Column('reccurence_delta_temps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('comptes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comptes')
    op.drop_table('transactions')
    # ### end Alembic commands ###
